<?php

use Krystal\Form\Element;

?>

<h2 class="page-header"><?php $this->show('Generate module skeleton'); ?></h2>

<?php if ($flashBag->has('success')): ?>
<div class="alert alert-success" role="alert"><i class="glyphicon glyphicon-ok"></i> <?php echo $flashBag->get('success'); ?></div>
<?php endif; ?>

<form class="form-horizontal" autocomplete="off" method="POST">
  <fieldset>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label"><?php $this->show('Module name'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('module', null, array('class' => 'form-control')); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" onclick="this.form.submit()" class="btn btn-primary"><?php $this->show('Generate'); ?></button>
      </div>
    </div>
  </fieldset>
</form>
