
<h2 class="page-header"><?php $this->show('Welcome to code generator'); ?></h2>
<p><small><?php $this->show('This tool can help you to generate common code templates'); ?></small></p>

<div class="row">
    <?php foreach ($items as $item): ?>
    <div class="col-lg-3">
        <div class="scaffold-item">
            <h4><?php $this->show($item['name']); ?></h4>

            <p><?php $this->show($item['description']); ?></p>
            <p>
                <a class="btn btn-primary btn-lg" href="<?= $this->url($item['route']); ?>"><?php $this->show('Generate'); ?></a>
            </p>
        </div>
    </div>
    <?php endforeach; ?>
</div>
